[book]
title        = "APPLICABILITY OF A CHANGE OF DIRECTION ABILITY FIELD TEST IN SOCCER ASSISTANT REFEREES"
authors      = ["zz"]
language     = "zh"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://zzzxj12138.github.io/02/"